config { 
    type: "table",
    name: "amazon_coffee_machines_product_details_current",
    schema: "amazon_silver",
    clusterBy: ["asin"],
    tags: ["silver", "amazon", "products"]
}

WITH ranked AS (
  SELECT
    *,
    ROW_NUMBER() OVER (
      PARTITION BY asin
      ORDER BY extracted_at DESC
    ) AS rn
  FROM ${ref("amazon_coffee_machines_product_details_flat")}
)

SELECT
  * EXCEPT (rn)
FROM ranked
WHERE rn = 1
